### ISSUE TITLE
关于校园巴士页面

### ISSUE THREAD

**Issue by 2013xile** [zhaoweizhong/LifeAtSUSTech#1]
想法挺赞的，有没有考虑做成微信小程序，前天小程序开放个人注册了。
另外为什么采用php开发呢，好像没有需要和后端交互的地方吧，为什么不用js
另外php和html耦合太严重了 可以考虑用模板引擎进行前后端分离

**Comment by zhaoweizhong** [comment]
目前没有后端，将来想要和校BBS整合，所以采用php，到时候有可能顺便把这个重新用lavarel写一遍

**Comment by 2013xile** [comment]
你这里用php没必要呀，用js就可以完成这一系列的逻辑判断了，这和以后写论坛也不冲突吧，感觉把前端的东西用后端去写了。小程序方面有想法吗？

**Comment by zhaoweizhong** [comment]
哈哈主要是我对js不如php熟悉😁<br>
最近忙BBS，所以小程序再说吧
